@echo off
echo Application Regression test stared
echo Regression test 1....
echo Regression test 2....
echo Regression test 3....
echo Regression test 4....
echo Regression test 5....
echo All Regression tests completed successfully